#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Thulani.Resource", IsApplication=true)]

namespace Thulani
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth.Resource.Animation.slide_in_right = global::Thulani.Resource.Animation.slide_in_right;
			global::Xamarin.Auth.Resource.Animation.slide_out_left = global::Thulani.Resource.Animation.slide_out_left;
			global::Xamarin.Auth.Resource.Drawable.ic_arrow_back = global::Thulani.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth.Resource.Id.webview = global::Thulani.Resource.Id.webview;
			global::Xamarin.Auth.Resource.Layout.activity_webview = global::Thulani.Resource.Layout.activity_webview;
			global::Xamarin.Auth.Resource.String.title_activity_webview = global::Thulani.Resource.String.title_activity_webview;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070002
			public const int preferredContact_array = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int title_array = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int typeOfID_array = 2131165185;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ekbackground3_logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ekulogo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fbIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_arrow_back = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int iconMain = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icons = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int loginIcon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int myButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int settingIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int settings = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int splashimage = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080017
			public const int LoginimageView = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int button1 = 2131230746;
			
			// aapt resource value: 0x7f080015
			public const int buttonCRM = 2131230741;
			
			// aapt resource value: 0x7f080029
			public const int buttonChangePassword = 2131230761;
			
			// aapt resource value: 0x7f080027
			public const int buttonEditProfile = 2131230759;
			
			// aapt resource value: 0x7f08001c
			public const int buttonFacebook = 2131230748;
			
			// aapt resource value: 0x7f08000f
			public const int buttonFacebookSignup = 2131230735;
			
			// aapt resource value: 0x7f080028
			public const int buttonPreferences = 2131230760;
			
			// aapt resource value: 0x7f080026
			public const int buttonRegister = 2131230758;
			
			// aapt resource value: 0x7f080012
			public const int buttonResetPass = 2131230738;
			
			// aapt resource value: 0x7f080004
			public const int buttonSavePassword = 2131230724;
			
			// aapt resource value: 0x7f080016
			public const int buttonSettings = 2131230742;
			
			// aapt resource value: 0x7f080014
			public const int buttonSiyakhokha = 2131230740;
			
			// aapt resource value: 0x7f08001d
			public const int editTextCellNumber = 2131230749;
			
			// aapt resource value: 0x7f080006
			public const int editTextCellNumberF = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int editTextConfirmPassword = 2131230723;
			
			// aapt resource value: 0x7f080011
			public const int editTextEmail = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int editTextEmailF = 2131230725;
			
			// aapt resource value: 0x7f080023
			public const int editTextIDPassport = 2131230755;
			
			// aapt resource value: 0x7f08000c
			public const int editTextIDPassportF = 2131230732;
			
			// aapt resource value: 0x7f08001f
			public const int editTextInitials = 2131230751;
			
			// aapt resource value: 0x7f080008
			public const int editTextInitialsF = 2131230728;
			
			// aapt resource value: 0x7f080020
			public const int editTextName = 2131230752;
			
			// aapt resource value: 0x7f080009
			public const int editTextNameF = 2131230729;
			
			// aapt resource value: 0x7f080002
			public const int editTextNewPassword = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int editTextOldPassword = 2131230721;
			
			// aapt resource value: 0x7f080018
			public const int editTextPass = 2131230744;
			
			// aapt resource value: 0x7f080025
			public const int editTextPassword = 2131230757;
			
			// aapt resource value: 0x7f08000e
			public const int editTextPasswordF = 2131230734;
			
			// aapt resource value: 0x7f080021
			public const int editTextSurname = 2131230753;
			
			// aapt resource value: 0x7f08000a
			public const int editTextSurnameF = 2131230730;
			
			// aapt resource value: 0x7f080013
			public const int imageViewHomeIcon = 2131230739;
			
			// aapt resource value: 0x7f080024
			public const int spinnerPreferredContact = 2131230756;
			
			// aapt resource value: 0x7f08000d
			public const int spinnerPreferredContactF = 2131230733;
			
			// aapt resource value: 0x7f08001e
			public const int spinnerTitle = 2131230750;
			
			// aapt resource value: 0x7f080007
			public const int spinnerTitleF = 2131230727;
			
			// aapt resource value: 0x7f080022
			public const int spinnerTypeOfID = 2131230754;
			
			// aapt resource value: 0x7f08000b
			public const int spinnerTypeOfIDF = 2131230731;
			
			// aapt resource value: 0x7f08001b
			public const int textViewCreateAccount = 2131230747;
			
			// aapt resource value: 0x7f080010
			public const int textViewForgetPass = 2131230736;
			
			// aapt resource value: 0x7f080019
			public const int textViewForgetPassword = 2131230745;
			
			// aapt resource value: 0x7f080000
			public const int webview = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChangePassword = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FacebookSignUP = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ForgetPass = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Home = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RegisterNewUser = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int spinnerLayout = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int preferredContact_prompt = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int title_activity_webview = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int title_prompt = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int typeOfID_prompt = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int spinnerTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
